# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d5f7beba6a260204bf949782e7ca4e6b469bdd45ec4a15cdbd6e54cb195c76950f86b4da3e839e230fe1f6ab6cd2b6dffc203223ff36259b8fcfeb71c0e1129

test:
  secret_key_base: ad4025cd8883fe48c375a6115c383d8d406374bfab6e408713fd68fb7f42732812ca52ca7e466db31a450feedcdf2a80ba19870cab200575488cbb5ff80ac6f0

production:
  secret_key_base: 201aa17fd48bb9d8219bb1a33f0972f3aa1a94de03ba8679b4e2ca702e0924026b6ec5ebb99e562e5730258fef079648c2e10ae6369f029859e8c5c04c349692
